= JavaScript: Getting Started by Mark Zamoyta
Lars Vogel(c) 2016 vogella GmbH
Version 0.3, 17.05.2021
:sectnums:
:toc:
:toclevels: 4


== JavaScript: Getting Started by Mark Zamoyta

=== Course Overview

==== Course Overview

JavaScript is the language of the web supported by all major browsers, but tools exist to take JavaScript far beyond web pages. You can create native smartphone and tablet apps, desktop apps for Windows and Mac, and even server‑side apps using JavaScript.


=== Introduction to JavaScript

==== Introduction

You may have heard of Unity, a popular game engine for 3D and 2D games. JavaScript is supported as a programming language for this engine. For large business applications, JavaScript is popular and has been embraced by a scalable language called *TypeScript*. This language is a superset of JavaScript, so you'll need to understand JavaScript well in order to write large‑scale business applications and other software using TypeScript.

JavaScript is not just for applications which run in browsers on the web. You can also create native applications for smartphones and tablets using JavaScript. A popular technology for this is *Apache Cordova*. JavaScript can also be used to create full‑fledged applications for the Mac and Windows desktops. There's no need for a browser at all. A popular technology to accomplish this is *Electron*. Writing server‑side code can also be accomplished in JavaScript. You can create web servers, web APIs, and other services using a technology called Node.js.

==== Installing Development Software

* git
* nodejs & npm
* visual studio code

==== Hello World Project from GitHub

* npm install
* npm run start

==== Our Sample Website

* npm install
* npm run start

=== JavaScript Beginnings

=== Variables and Constants

==== var keyword

=== Types and Operators

==== Operator Precedence

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence

> Manipulating String

=== Functions

* Symbol data type in Java Script




